config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'
  get 'mailbox/inbox' => "mailbox#inbox", as: :mailbox_inbox
  get 'mailbox/sent' => "mailbox#sent", as: :mailbox_sent
  get 'mailbox/trash' => "mailbox#trash", as: :mailbox_trash
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        acts_as_messageable

        def mailboxer_name
          self.name
        end

        def mainboxer_email(object)
          self.email
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :mailbox, :conversation

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end
  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end
  protected

  def configure_permitted_parameters
    [:account_update, :sign_up].each do |i|
      devise_parameter_sanitizer.permit(:name)
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  private

  def message_params
    params.require(:message).permit(:body, :subject)
  end

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!
  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mainlbox.sent
    @active = :sent
  end

  def trash
    @trash = mainbox.trash
    @active = :trash
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-success"
      when :info then "alert alert-info"
      when :alert then "alert alert-danger"
      when :warning then "alert alert-warning"
    end
  end

  def active_page(active_page)
    @active == active_page ? "active" : ""
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    #capture amount of unread messages
    #using Mailboxer
    mailbox.inbox(unread: true).count(:id, distinct: true)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conversations/_conversation.html.haml
.media
  .media-left
    %a{:href => "#"}
      %img.media-object{:alt => "...", :src => "http://placehold.it/64x64"}/
  .media-body
    %h4.media-heading
      = conversation.originator.name
      %br/
      %small
        %b Subject:
        = conversation.subject
      %br/
      %small
        %b Date:
        = conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p")
    = truncate conversation.messages.last.body, length: 145
    = link_to "View", conversation_path(conversation)

app/views/conversations/_form.html.haml
= form_for :conversation, url: :conversations, html: { class: "" } do |f|
  .form-group
    = f.label :recipients
    = f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })
  .form-group
    = f.label :subject
    = f.text_field :subject, placeholder: "Subject", class: "form-control"
  .form-group
    = f.label :message
    = f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4
  = f.submit "Send Message", class: "btn btn-success"

app/views/conversations/_messages.html.haml
- @receipts.each do |receipt|
  - message = receipt.message
  .media
    .media-left
      / user avators can go here
      %a{:href => "#"}
        %img.media-object{:alt => "...", :src => "http://placehold.it/64x64"}/
    .media-body
      %h4.media-heading
        = message.sender.name
        %br/
        %small
          %b Subject:
          = message.subject
        %br/
        %small
          %b Date:
          = message.created_at.strftime("%A, %b %d, %Y at %I:%M%p")
      = message.body

app/views/conversations/new.html.haml
= render partial: 'mailbox/folder_view', locals: {is_conversation: true}

app/views/conversations/show.html.haml
.row
  .spacer
  .col-md-6
    = link_to "Compose", new_conversation_path, class: "btn btn-success"
  .col-md-6.text-right
    - if conversation.is_trashed?(current_user)
      = link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post
    - else
      = link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post, |
        data: {confirm: 'Are you sure?'}                                                                        |
.row
  .spacer
  .col-md-4
    .panel.panel-default
      .panel-body
        = render 'mailbox/folders'
  .col-md-8
    .panel.panel-default
      .panel-body
        = render partial: 'messages'
      .panel-footer
        / Reply Form
        = form_for :message, url: reply_conversation_path(conversation) do |f|
          .form-group
            = f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control"
          = f.submit "Reply", class: 'btn btn-danger pull-right'
        .clearfix

app/views/layouts/_nav.html.haml
/ Fixed navbar
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Messenger", root_path, class: "navbar-brand"
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.pull-right
        - if user_signed_in?
          %li= link_to "Hello, #{current_user.name}", "#"
          %li= link_to "Inbox", mailbox_inbox_path
          %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li.active= link_to "Login", new_user_session_path
          %li= link_to "Sign up", new_user_registration_path
    / /.nav-collapse

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title InboxApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
  = render 'layouts/nav'
  - flash.each do |key, value|
    %div{:class => "text-center #{flash_class(key)}"}
      = value

  .container
    = yield

app/views/mailbox/_folder_view.html.haml
.row
  .spacer
  .col-md-12
    = link_to "Compose", new_conversation_path, class: "btn btn-success"
    .spacer
  .col-md-4
    .panel.panel-default
      .panel-body
        = render 'mailbox/folders'
  .col-md-8
    .panel.panel-default
      .panel-body
        - if is_conversation
          = render 'conversations/form'
        - else
          = render partial: 'conversations/conversation', collection: messages

app/views/mailbox/_folders.html.haml
%ul.nav.nav-pills.nav-stacked
  %li{:class => "#{active_page(:inbox)}"}
    = link_to mailbox_inbox_path do
      %span.label.label-danger.pull-right= unread_messages_count
      %em.fa.fa-inbox.fa-lg
      %span Inbox
  %li{:class => "#{active_page(:sent)}"}
    = link_to mailbox_sent_path do
      %em.fa.fa-paper-plane-o.fa-lg
      %span Sent
  %li{:class => "#{active_page(:trash)}"}
    = link_to mailbox_trash_path do
      %em.fa.fa-trash-o.fa-lg
      %span Trash

app/views/mailbox/inbox.html.haml
= render partial: 'mailbox/folder_view', locals: {is_conversation: false, messages: @inbox}

app/views/mailbox/sent.html.haml
= render partial: 'mailbox/folder_view', locals: {is_conversation: false}

app/views/mailbox/trash.html.haml
= render partial: 'mailbox/folder_view', locals: {is_conversation: false}

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml